# Install `task` from https://taskfile.dev
# Run `task --list` to start.

version: "2.6"
expansions: 3

env:
  DOCKER_IMAGE: cogito

vars:
  DATE: '{{ now | date "2006-01-02" }}'
  COMMIT:
    sh: git log -n 1 --format=%h
  REPO: github.com/Pix4D/cogito
  BUILD_INFO: "Tag: {{.TAG}}, commit: {{.COMMIT}}, build date: {{.DATE}}"
  LDFLAGS: -w -X '{{.REPO}}/resource.buildinfo={{.BUILD_INFO}}'
  GOTESTSUM:
    sh: which gotestsum; true
  TESTRUNNER: "{{if .GOTESTSUM}}{{.GOTESTSUM}}{{else}}go test{{end}}"

tasks:
  default:
    deps: [test]
    desc: Sensible defaults if you invoke `task` without arguments.
  test:
    desc: Run the tests.
    cmds:
      - "{{.TESTRUNNER}} ./..."
  copydir:
    desc: Build copydir.
    dir: bin
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" ../cmd/copydir
  build:
    deps: [copydir]
    desc: Build on the local machine.
    dir: bin
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" ../cmd/check
      - go build -ldflags "{{.LDFLAGS}}" ../cmd/in
      - go build -ldflags "{{.LDFLAGS}}" ../cmd/out
      - go build -ldflags "{{.LDFLAGS}}" ../cmd/hello
  docker-build:
    desc: Build the Docker image.
    cmds:
      - docker build --build-arg BUILD_INFO --tag $DOCKER_IMAGE .
    env:
      BUILD_INFO: "{{.BUILD_INFO}}"
  docker-smoke:
    desc: Simple smoke test of the Docker image.
    cmds:
      - echo '{{.INPUT}}' | docker run --rm --interactive cogito /opt/resource/check
      - echo
    vars:
      INPUT: '{ "source": { "owner": "foo", "repo": "bar", "access_token": "123"} }'
  docker-login:
    silent: true
    cmds:
      - echo "Logging in to DockerHub"
      - docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN 2> /dev/null
  docker-push:
    deps: [docker-login]
    cmds:
      - docker tag $DOCKER_IMAGE $DOCKER_ORG/$DOCKER_IMAGE:$DOCKER_TAG
      - echo Pushing $DOCKER_ORG/$DOCKER_IMAGE:$DOCKER_TAG 
      - docker push $DOCKER_ORG/$DOCKER_IMAGE:$DOCKER_TAG
      - |-
        if [ -n "$DOCKER_LATEST" ]; then
            docker tag $DOCKER_IMAGE $DOCKER_ORG/$DOCKER_IMAGE:$DOCKER_LATEST
            echo Pushing $DOCKER_ORG/$DOCKER_IMAGE:$DOCKER_LATEST
            docker push $DOCKER_ORG/$DOCKER_IMAGE:$DOCKER_LATEST
        fi
    env:
      DOCKER_TAG:
        sh: ci/git-ref-to-docker-tag.sh
      DOCKER_LATEST:
        sh: ci/git-latest.sh
