meta:

  gh-status_handlers: &gh-status-handlers
    on_success:
      put: gh-status
      inputs: [repo.git]
      params: {state: success}
    on_failure:
      put: gh-status
      inputs: [repo.git]
      params: {state: failure}
    on_error:
      put: gh-status
      inputs: [repo.git]
      params: {state: error}
    on_abort:
      put: gh-status
      inputs: [repo.git]
      params: {state: abort}

resource_types:

- name: cogito
  type: registry-image
  # For production use, `24h` is a good tradeoff to get a new release with a maximum delay
  # of 24h. Here we parametrize it to work around a concourse bug when doing development.
  # See CONTRIBUTING for details
  check_every: ((cogito-image-check_every))
  source:
    repository: pix4d/cogito
    tag: ((cogito-tag))

resources:

- name: gh-status
  type: cogito
  # Since check is a no-op, we do not check, to reduce load on the system.
  check_every: never
  source:
    # Optional, for debugging only.
    log_level: debug
    owner: ((github-owner))
    repo: ((repo-name))
    access_token: ((oauth-personal-access-token))
    gchat_webhook: ((gchat_webhook))

- name: repo.git
  type: git
  source:
    # If repo is public:
    uri: https://github.com/((github-owner))/((repo-name)).git
    # If repo is private:
    #uri: git@github.com:((github-owner))/((repo-name)).git
    #private_key: ((ssh-key))
    branch: ((branch))

jobs:

  - name: autocat
    <<: *gh-status-handlers
    plan:
      - get: repo.git
        trigger: true
      - put: gh-status
        inputs: [repo.git]
        params: {state: pending}
      - task: will-fail
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: alpine }
          run:
            path: /bin/sh
            args:
              - -c
              - |
                set -o errexit
                echo Hello from autocat
                exit 1

  - name: motormouse
    <<: *gh-status-handlers
    plan:
      - get: repo.git
        trigger: true
      - put: gh-status
        inputs: [repo.git]
        params: {state: pending}
      - task: will-succeed
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: alpine }
          run:
            path: /bin/sh
            args:
              - -c
              - |
                set -o errexit
                echo Hello from motormouse
                exit 0
