# See https://docs.github.com/en/actions/reference/

on: [push]

name: ci

env:
  go-version: 1.26.x
  golangci-version: v2.11.4
  gotestsum-version: v1.13.0
  task-version: v3.40.0

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          # By default, actions/checkout will persist the GITHUB_TOKEN, so that further
          # steps in the job can perform authenticated git commands (that is: WRITE to
          # the repo). Following the Principle of least privilege, we disable this as long
          # as we don't need it.
          persist-credentials: false
      # Installing Go must be done AFTER checking out the code, in order to have
      # caching working!
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # ratchet:actions/setup-go@v6
        with:
          go-version: ${{ env.go-version }}
      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@${{ env.task-version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # ratchet:golangci/golangci-lint-action@v9
        with:
          version: ${{ env.golangci-version }}
      - run: task build
      - run: go install gotest.tools/gotestsum@${{ env.gotestsum-version }}
      - run: task test:all
        env:
          COGITO_TEST_OAUTH_TOKEN: ${{ secrets.COGITO_TEST_OAUTH_TOKEN }}
          COGITO_TEST_GCHAT_HOOK: ${{ secrets.COGITO_TEST_GCHAT_HOOK }}
          COGITO_TEST_GH_APP_PRIVATE_KEY: |
            ${{ secrets.COGITO_TEST_GH_APP_PRIVATE_KEY }}
      - run: task docker:build
      - run: task docker:smoke
      - run: task docker:login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      - run: task docker:push
      - run: task docker:maybe-push-release
      - run: task ci:teardown
        # ALWAYS run this step, also if any previous step failed.
        if: always()
